### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by tablecell** [SundownDEV/Daimyo#1]
index.php
````
<?php
require __DIR__.'/app/system.php';

require_once __DIR__.'/vendor/autoload.php';

$app = new \App\Application($debug = true);


// Use REGEX in routes, see Braumus' doc for more info
$app->get('/hello/([a-zA-Z0-9_-]+)', function ($name) use ($app) {
    $app->render('hello', ['title' => 'Hello route', 'name' => $name]);
});

```
curl  http://localhost/hello/jack

**Comment by SundownDEV** [comment]
Hello,

can you c/c the entire php error please ?

**Comment by SundownDEV** [comment]
Try this (I updated app/system.php)
~~~php
$app->get('/hello/([a-zA-Z0-9_-]+)', function ($name) use ($app) {
    $app->render(['view' => 'hello'], ['title' => 'Hello route', 'name' => $name]);
});
~~~

**Comment by tablecell** [comment]
update app/system.php
 PHP\php-5.6.20-nts-Win32-VC11-x86\php -c  php-5.6.20-nts-Win32-VC11-x86\php.ini
-S localhost:80
Fatal error: Default value for parameters with a class type hint can only be NULL in  Daimyo-master\app\system.php on line 53

php7 -S localhost:80 

sovled the syntax issue 
but templates path seems not correct 

Fatal error: Uncaught Twig_Error_Loader: The " Daimyo-master\index.php/views/" directory does not exist

**Comment by SundownDEV** [comment]
Updated system.php again, $app->views wasn't update since I moved /views/ to /app/ folder, can you try again and tell me?

Thanks

**Comment by tablecell** [comment]
Fatal error: Uncaught Twig_Error_Loader: The " Daimyo-master\public\index.php/app/views/" directory does not exist 

Daimyo-master\app\system.php  line 58 
```
	$this->webroot = str_replace('/public/index.php', '', $_SERVER['SCRIPT_FILENAME']);
```
i change to 
```
$this->webroot = dirname(dirname($_SERVER['SCRIPT_FILENAME'])); 
```
because the windows platform directory seperator \   
str_replace('/public/index.php', 'Daimyo-master\public\index.php' ) not work correctly 

dirname(dirname($_SERVER['SCRIPT_FILENAME']));   works fine both windows/linux platform

**Comment by SundownDEV** [comment]
Yeah I didn't think about windows users at all, thanks for the issue.

Do not hesitate to give review or fork the framework! :)
